[package]
name = "my_teloxide_bot"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.9", features = ["macros"] }
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
pretty_env_logger = "0.4"
log = "0.4"